### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by STBoyden** [umurgdk/ddnotes#3]
While using ddnotes, I noticed that an error saying "/foo/bar/ddnotes: line 72: alacritty: command not found". Is this meant to be in the list of dependencies in the README?

**Comment by umurgdk** [comment]
Yes unfortunately i didn't had a time to clean the codes. So `alacritty` is a terminal emulator, which I use. I will update the script when I have time to support for other terminal emulators like (urxvt, gnome-terminal, st) out of the box.

**Comment by STBoyden** [comment]
Alright, thank-you!
